services:

  nginx:
      build: ./nginx
      container_name: nginx
      #端口 主机：容器
      ports:
        - "80:80"
      links:
        - "php"


  php:
      build: ./php
      container_name: php
      ports:
        - "9000:9000"
      links:
        - "mysql"
        - "memcache"
        - "redis"
        - "rabbitmq"


  mysql:
      build: ./mysql
      container_name: mysql
      ports:
        - "3306:3306"
      environment:
        - MYSQL_USER=root
        - MYSQL_ROOT_PASSWORD=root

  memcache:
      build: ./memcache
      container_name: memcache
      ports:
        - "11211:11211"

  redis:
      build: ./redis
      container_name: redis
      ports:
        - "6379:6379"

  phpmyadmin:
      image: phpmyadmin
      container_name: phpmyadmin
      ports:
        -  "8080:80"
      links:
        - "mysql"
        - "php"
      environment:
        - PMA_ARBITRARY=1

  rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      hostname: rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
      environment:
        - HOSTNAME=rabbitmq
        - RABBITMQ_NODENAME=rabbitmq
